# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastProxSL1 <- function(y, lambda) {
    .Call(`_SlopeSolver_FastProxSL1`, y, lambda)
}

solveSlope <- function(x, y, lambda) {
    .Call(`_SlopeSolver_solveSlope`, x, y, lambda)
}

